SELECT * FROM RETAIL_SALES.RETAIL_SALES;

SELECT COUNT(*) FROM RETAIL_SALES.RETAIL_SALES
LIMIT 10;
SELECT * FROM RETAIL_SALES.RETAIL_SALES
WHERE 
ï»¿transactions_id IS NULL
OR
SALE_TIME IS NULL 
OR
GENDER IS NULL
OR
CATEGORY IS NULL 
OR 
SALE_DATE IS NULL
OR 
TOTAL_SALE IS NULL;

-- DATA EXPLORATION 

USE RETAIL_SALES;
SELECT COUNT(*) AS TOTAL_SALES FROM RETAIL_SALES;
SELECT COUNT( DISTINCT customer_id) AS TOTAL_SALES FROM RETAIL_SALES;
SELECT  COUNT( DISTINCT CATEGORY) AS TOTAL_SALES FROM RETAIL_SALES;

SELECT * FROM RETAIL_SALES.RETAIL_SALES
WHERE SALE_DATE  = '2022-11-05';

SELECT CATEGORY, QUANTIY, GENDER ,DAY(SALE_DATE),YEAR(SALE_DATE) FROM RETAIL_SALES.RETAIL_SALES
WHERE CATEGORY = 'CLOTHING' AND QUANTIY >= '4'
ORDER BY CATEGORY;

SELECT CATEGORY, SUM(TOTAL_SALE) AS NET_SALE, COUNT(*) AS TOTAL_ORDERS
FROM RETAIL_SALES.RETAIL_SALES
GROUP BY CATEGORY;

SELECT ROUND(AVG(AGE),3), CATEGORY FROM RETAIL_SALES.RETAIL_SALES
WHERE CATEGORY ='BEAUTY';

SELECT * FROM RETAIL_SALES.RETAIL_SALES
WHERE TOTAL_SALE > 1000;

SELECT CATEGORY, GENDER, COUNT(*) AS TOTAL_TRANS FROM RETAIL_SALES.RETAIL_SALES
GROUP BY CATEGORY,GENDER
ORDER BY 1;

SELECT YEAR(TOTAL_SALE) AS `YEAR`,
MONTH(TOTAL_SALE) AS `MONTH`,
AVG(TOTAL_SALE)AS AVG_SALE,
RANK() OVER( PARTITION BY MONTH(TOTAL_SALE) ORDER BY AVG(TOTAL_SALE) ASC ) AS `RANK`
FROM RETAIL_SALES.RETAIL_SALES
GROUP BY 1,2;

SELECT CUSTOMER_ID, SUM(TOTAL_SALE) AS TOTAL_SALES FROM RETAIL_SALES.RETAIL_SALES
GROUP BY 1
ORDER BY 2 DESC;

SELECT CATEGORY, COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CS
FROM RETAIL_SALES.RETAIL_SALES
GROUP BY CATEGORY;

WITH HOURLY_SALE
AS 
(SELECT *, 
CASE 
WHEN EXTRACT(HOUR FROM SALE_TIME) <12 THEN 'MORNING'
WHEN  EXTRACT(HOUR FROM SALE_TIME)BETWEEN 12 AND 17 THEN 'AFTERNOON'
ELSE 'EVENING' 
END AS SIFT 
FROM RETAIL_SALES.RETAIL_SALES) SELECT  SIFT, COUNT(*) AS TOTAL_ORDERS
FROM HOURLY_SALE
GROUP BY SIFT


